apiVersion: skaffold/v2alpha4
kind: Config

build:
  googleCloudBuild:
    projectId: toolbox-272913
  artifacts:
    - image: "gcr.io/toolbox-272913/taxman-backend"
      docker:
        dockerfile: dockerfiles/Dockerfile.jvm
profiles:
  - name: base-with-postgres
    deploy:
      kubeContext: gke_toolbox-272913_europe-west1-d_toolbox-cluster-6bce7d8a
      kustomize:
        paths: [./local-postgres-k8s, ./k8s]
  - name: base
    deploy:
      kubeContext: gke_toolbox-272913_europe-west1-d_toolbox-cluster-6bce7d8a
      kustomize:
        paths: [./k8s]
  - name: local-postgres
    build:
      local:
        useDockerCLI: true
        push: false
    deploy:
      kubeContext: minikube
      kustomize:
        paths: [./local-postgres-k8s]
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: dockerfiles/Dockerfile.dummy
