apiVersion: skaffold/v2alpha4
kind: Config

build:
  local:
    useDockerCLI: true
    push: false
  artifacts:
    - image: "taxman-backend"
      docker:
        dockerfile: dockerfiles/Dockerfile.jvm
profiles:
  - name: local-postgres
    deploy:
      kubeContext: minikube
      kustomize:
        paths: [./local-postgres-k8s, ./k8s]
  - name: base
    deploy:
      kubeContext: minikube
      kustomize:
        paths: [./k8s]
