apiVersion: skaffold/v2alpha4
kind: Config

build:
  local:
    useDockerCLI: true
    push: true
  artifacts:
    - image: "taxman-backend"
      jib:
        type: "gradle"
        project: "taxonomy-manager-rest-server"
deploy:
  kustomize:
    paths:
      - k8s/
