apiVersion: skaffold/v2alpha4
kind: Config

build:
  local:
    useDockerCLI: true
    push: true
  artifacts:
    - image: "taxman-backend"
      docker:
        dockerfile: dockerfiles/Dockerfile.jvm
deploy:
  kustomize:
    paths:
      - k8s/
