apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxman-backend
  labels:
    app: taxman-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxman-backend
  template:
    metadata:
      labels:
        app: taxman-backend
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:11.4
          command: ['sh', '-c',
                    'until pg_isready -h postgres -p 5432;
               do echo waiting for database; sleep 2; done;']
      tolerations:
        - key: "sku"
          operator: "Equal"
          value: "jenkins"
          effect: "NoSchedule"
      nodeSelector:
        beta.kubernetes.io/os: "linux"
        role: "jobs"
      containers:
        - name: backend
          imagePullPolicy: Always
          image: "gcr.io/toolbox-272913/taxman-backend"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 15
          envFrom:
            - configMapRef:
                name: taxman-backend-db-config
            - secretRef:
                name: taxman-backend-db-secrets
          env:
            - name: QUARKUS_DATASOURCE_DRIVER
              value: "org.postgresql.Driver"
          ports:
            - containerPort: 8080
              name: http
