apiVersion: v1
kind: Service
metadata:
  name: taxman-backend
spec:
  type: NodePort
  selector:
    app: taxman-backend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
